app:
  server:
    name: glashfish
    detail: this is glasfish for production

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/general?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ayaznacafli
    password: ayaz1997
