app:
  server:
    name: tomcat
    detail: this is tomcat for dev

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/general?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ayaz1997
